# generate cmake header

def generate_export_header(
        name,
        library_name,
        output = None,
        prefix = "",
        visibility = ["//visibility:public"]):
    """Generates a CMake GenerateExportHeader-compatible header.

    Args:
        name: Bazel target name.
        library_name: Library name used to construct the macro names.
        output: Generated header path. Defaults to <library_name>_export.h.
        prefix: Optional prefix for all generated macros.
        visibility: Bazel visibility.
    """

    if output == None:
        output = "export.hpp"

    macro = prefix + library_name.upper()

    export_macro = macro + "_EXPORT"
    no_export_macro = macro + "_NO_EXPORT"
    deprecated_macro = macro + "_DEPRECATED"
    deprecated_export_macro = deprecated_macro + "_EXPORT"
    deprecated_no_export_macro = deprecated_macro + "_NO_EXPORT"
    static_define = macro + "_STATIC_DEFINE"
    no_deprecated = macro + "_NO_DEPRECATED"

    native.genrule(
        name = name + "_generate",
        outs = [output],
        cmd = """
cat > "$@" <<'EOF'
#ifndef {guard}
#define {guard}

/*
 * Generated by Bazel as a replacement for CMake's
 * GenerateExportHeader.cmake.
 */

/*
 * RSL is built statically by Bazel.
 *
 * CMake's GenerateExportHeader defines the export-related
 * macros to nothing for STATIC libraries.
 */
#define {export_macro}
#define {no_export_macro}

/*
 * Deprecation attributes.
 */
#if defined(__GNUC__) || defined(__clang__)
#  define {deprecated_macro} __attribute__((__deprecated__))
#elif defined(_MSC_VER)
#  define {deprecated_macro} __declspec(deprecated)
#else
#  define {deprecated_macro}
#endif

#define {deprecated_export_macro} {deprecated_macro}
#define {deprecated_no_export_macro} {deprecated_macro}

/*
 * Defined by CMake's GenerateExportHeader when requested.
 * Kept here for compatibility.
 */
#define {static_define}

/*
 * Do not define {no_deprecated} unless the build explicitly
 * requests removal of deprecated APIs.
 */

#endif /* {guard} */
EOF
""".format(
            guard = export_macro + "_H",
            export_macro = export_macro,
            no_export_macro = no_export_macro,
            deprecated_macro = deprecated_macro,
            deprecated_export_macro = deprecated_export_macro,
            deprecated_no_export_macro = deprecated_no_export_macro,
            static_define = static_define,
            no_deprecated = no_deprecated,
        ),
        visibility = visibility,
    )

    native.cc_library(
        name = name,
        hdrs = [":" + name + "_generate"],
        includes = ["."],
        visibility = visibility,
    )
