load("@com_github_mvukov_rules_ros2//ros2:cc_defs.bzl", "ros2_cpp_library")
load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "libcap",
    linkopts = ["-lcap"],
)

ros2_cpp_library(
    name = "realtime_tools",
    srcs = glob(
        [
            "realtime_tools/src/*.cpp",
        ],
    ),
    hdrs = glob([
        "realtime_tools/include/realtime_tools/*.hpp",
    ]),
    strip_include_prefix = "realtime_tools/include",
    visibility = ["//visibility:public"],
    deps = [
        ":libcap",
        "@fmt",
        "@ros2_rclcpp//:rclcpp",
        "@ros2_rclcpp//:rclcpp_action",
        "@ros2_rcpputils//:rcpputils",
    ],
)
